import { collection, getDocs, doc, setDoc } from "firebase/firestore";
import { db } from "../firebase";

const seedData = [
  // Groceries
  {
    name: "Whole Wheat Bread",
    category: "groceries",
    price: 45,
    originalPrice: 55,
    discount: 18,
    rating: 4.5,
    reviewCount: 234,
    unit: "1 Loaf",
    imageColor: "#92400e",
    description: "Freshly baked whole wheat bread made with 100% whole grain flour. Rich in fiber and nutrients, perfect for sandwiches and toast.",
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    name: "Basmati Rice",
    category: "groceries",
    price: 89,
    originalPrice: 109,
    discount: 18,
    rating: 4.7,
    reviewCount: 189,
    unit: "1 kg bag",
    imageColor: "#854d0e",
    description: "Premium aged basmati rice with a delicate aroma and long, slender grains. Cooks fluffy and separate every time.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    name: "Extra Virgin Olive Oil",
    category: "groceries",
    price: 449,
    originalPrice: 599,
    discount: 25,
    rating: 4.8,
    reviewCount: 312,
    unit: "750 ml",
    imageColor: "#713f12",
    description: "Cold-pressed extra virgin olive oil from Mediterranean olives. Rich, fruity flavor perfect for cooking, dressings, and dipping.",
    inStock: true,
    featured: true,
    bestSeller: false,
  },
  {
    name: "Rolled Oats",
    category: "groceries",
    price: 149,
    originalPrice: 179,
    discount: 17,
    rating: 4.6,
    reviewCount: 156,
    unit: "1 kg",
    imageColor: "#78350f",
    description: "Whole grain rolled oats, perfect for overnight oats, porridge, granola, and baking. High in fiber and slow-release energy.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  // Fruits
  {
    name: "Organic Bananas",
    category: "fruits",
    price: 49,
    originalPrice: 65,
    discount: 25,
    rating: 4.4,
    reviewCount: 278,
    unit: "1 kg",
    imageColor: "#365314",
    description: "Sweet, ripe organic bananas. Naturally rich in potassium and vitamins. Great for smoothies, snacking, or baking.",
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    name: "Red Apples",
    category: "fruits",
    price: 129,
    originalPrice: 159,
    discount: 19,
    rating: 4.5,
    reviewCount: 421,
    unit: "1 kg",
    imageColor: "#14532d",
    description: "Crisp and sweet red apples, hand-picked at peak ripeness. High in antioxidants and dietary fiber.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    name: "Fresh Strawberries",
    category: "fruits",
    price: 199,
    originalPrice: 249,
    discount: 20,
    rating: 4.8,
    reviewCount: 198,
    unit: "250 g punnet",
    imageColor: "#166534",
    description: "Plump, juicy strawberries bursting with natural sweetness. Perfect fresh, with cream, in desserts, or blended into smoothies.",
    inStock: true,
    featured: true,
    bestSeller: false,
  },
  {
    name: "Alphonso Mangoes",
    category: "fruits",
    price: 299,
    originalPrice: 349,
    discount: 14,
    rating: 4.9,
    reviewCount: 143,
    unit: "1 kg",
    imageColor: "#15803d",
    description: "The king of mangoes — Alphonso variety with a rich, creamy texture and intense sweetness. Seasonal and limited availability.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  // Dairy
  {
    name: "Full Fat Milk",
    category: "dairy",
    price: 58,
    originalPrice: 65,
    discount: 11,
    rating: 4.6,
    reviewCount: 567,
    unit: "1 L",
    imageColor: "#1e3a5f",
    description: "Farm-fresh full fat milk, pasteurized and homogenized. Rich in calcium, protein, and essential vitamins for the whole family.",
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    name: "Greek Yogurt",
    category: "dairy",
    price: 120,
    originalPrice: 149,
    discount: 19,
    rating: 4.7,
    reviewCount: 234,
    unit: "500 g",
    imageColor: "#1e40af",
    description: "Thick, creamy Greek yogurt strained to perfection. High in protein, probiotic-rich, and delicious with honey, fruit, or granola.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    name: "Free-Range Eggs",
    category: "dairy",
    price: 99,
    originalPrice: 119,
    discount: 17,
    rating: 4.8,
    reviewCount: 489,
    unit: "12 pack",
    imageColor: "#1d4ed8",
    description: "Eggs from free-range hens with access to outdoor space. Richer yolks, better flavor, and higher nutritional value.",
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  {
    name: "Cheddar Cheese",
    category: "dairy",
    price: 349,
    originalPrice: 449,
    discount: 22,
    rating: 4.5,
    reviewCount: 267,
    unit: "400 g block",
    imageColor: "#1e3a8a",
    description: "Mature cheddar cheese aged for a minimum of 12 months. Sharp, tangy flavor with a firm, crumbly texture. Great for cooking or snacking.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  // Snacks
  {
    name: "Sea Salt Chips",
    category: "snacks",
    price: 30,
    originalPrice: 35,
    discount: 14,
    rating: 4.3,
    reviewCount: 612,
    unit: "150 g bag",
    imageColor: "#7f1d1d",
    description: "Thin-cut potato chips cooked in sunflower oil and seasoned with pure sea salt. The perfect crunch every time.",
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    name: "Dark Chocolate 70%",
    category: "snacks",
    price: 149,
    originalPrice: 199,
    discount: 25,
    rating: 4.8,
    reviewCount: 389,
    unit: "100 g bar",
    imageColor: "#991b1b",
    description: "Rich, intense dark chocolate made with 70% cacao. Single-origin beans, ethically sourced. High in antioxidants and magnesium.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    name: "Premium Mixed Nuts",
    category: "snacks",
    price: 499,
    originalPrice: 649,
    discount: 23,
    rating: 4.6,
    reviewCount: 201,
    unit: "500 g",
    imageColor: "#b91c1c",
    description: "A premium blend of cashews, almonds, walnuts, and pecans. Lightly roasted and unsalted. Packed with healthy fats and protein.",
    inStock: true,
    featured: true,
    bestSeller: false,
  },
  {
    name: "Air-Popped Popcorn",
    category: "snacks",
    price: 45,
    originalPrice: 59,
    discount: 24,
    rating: 4.4,
    reviewCount: 178,
    unit: "150 g",
    imageColor: "#dc2626",
    description: "Light and airy popcorn with zero oil and minimal calories. Lightly salted for flavor without the guilt.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  // Beverages
  {
    name: "Fresh Orange Juice",
    category: "beverages",
    price: 99,
    originalPrice: 129,
    discount: 23,
    rating: 4.6,
    reviewCount: 345,
    unit: "1 L carton",
    imageColor: "#7c2d12",
    description: "100% pure squeezed orange juice, no added sugar or preservatives. Rich in vitamin C and natural fruit sugars.",
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    name: "Organic Green Tea",
    category: "beverages",
    price: 249,
    originalPrice: 319,
    discount: 22,
    rating: 4.7,
    reviewCount: 212,
    unit: "50 tea bags",
    imageColor: "#9a3412",
    description: "Premium organic green tea from high-altitude Japanese farms. Light, grassy flavor with natural antioxidants and L-theanine.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    name: "Sparkling Water",
    category: "beverages",
    price: 55,
    originalPrice: 69,
    discount: 20,
    rating: 4.5,
    reviewCount: 423,
    unit: "1 L bottle",
    imageColor: "#c2410c",
    description: "Naturally carbonated mineral water from an alpine spring. Crisp, refreshing, and naturally rich in minerals. Zero calories.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    name: "Cold Brew Coffee",
    category: "beverages",
    price: 199,
    originalPrice: 249,
    discount: 20,
    rating: 4.8,
    reviewCount: 167,
    unit: "500 ml bottle",
    imageColor: "#ea580c",
    description: "Smooth, low-acidity cold brew coffee steeped for 20 hours. Rich, chocolatey flavor with a natural caffeine kick. Serve over ice.",
    inStock: true,
    featured: true,
    bestSeller: true,
  },
  // Personal Care
  {
    name: "Whitening Toothpaste",
    category: "personal-care",
    price: 89,
    originalPrice: 119,
    discount: 25,
    rating: 4.5,
    reviewCount: 534,
    unit: "100 g tube",
    imageColor: "#164e63",
    description: "Advanced whitening toothpaste with enamel-safe micro-polishing technology. Removes stains, strengthens enamel, and freshens breath.",
    inStock: true,
    featured: false,
    bestSeller: true,
  },
  {
    name: "Argan Oil Shampoo",
    category: "personal-care",
    price: 349,
    originalPrice: 499,
    discount: 30,
    rating: 4.7,
    reviewCount: 289,
    unit: "250 ml",
    imageColor: "#155e75",
    description: "Nourishing shampoo enriched with pure Moroccan argan oil. Repairs damaged hair, adds shine, and controls frizz. Sulfate-free.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    name: "Moisturizing Hand Cream",
    category: "personal-care",
    price: 179,
    originalPrice: 229,
    discount: 22,
    rating: 4.6,
    reviewCount: 198,
    unit: "75 ml tube",
    imageColor: "#0e7490",
    description: "Fast-absorbing hand cream with shea butter and vitamin E. Provides 24-hour moisture for soft, smooth hands. Non-greasy formula.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
  {
    name: "Foaming Face Wash",
    category: "personal-care",
    price: 299,
    originalPrice: 379,
    discount: 21,
    rating: 4.8,
    reviewCount: 267,
    unit: "150 ml",
    imageColor: "#0891b2",
    description: "Gentle foaming face wash with niacinamide and hyaluronic acid. Cleanses deeply while maintaining the skin's natural moisture barrier.",
    inStock: true,
    featured: false,
    bestSeller: false,
  },
];

const PRODUCT_IDS = [
  "product-01", "product-02", "product-03", "product-04",
  "product-05", "product-06", "product-07", "product-08",
  "product-09", "product-10", "product-11", "product-12",
  "product-13", "product-14", "product-15", "product-16",
  "product-17", "product-18", "product-19", "product-20",
  "product-21", "product-22", "product-23", "product-24",
];

export async function seedProductsIfEmpty() {
  const snap = await getDocs(collection(db, "products"));
  if (!snap.empty) return;
  await Promise.all(
    seedData.map((data, i) => setDoc(doc(db, "products", PRODUCT_IDS[i]), data))
  );
}
